spring:
  data:
      mongodb:
        uri: mongodb+srv://dfb-wallmart-44:jzxrg0kvcVCAk2NN@cluster0.rhfdr.mongodb.net/productos?retryWrites=true&w=majority
        
discount:
 palindromo: 50
 
server:
  port: 8090
